const HOST_ADDR = "34.64.149.19:3000";

// swagger/swagger.js
const swaggerJsdoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");
const packageJson = require("../package.json");

// Swagger 설정 옵션
const options = {
	definition: {
		openapi: "3.0.0",
		info: {
			title: "API Documentation", // API 제목
			version: packageJson.version,
			description: "Cafe API documentation generated by Swagger",
		},
		servers: [
			{
				url: `http://${HOST_ADDR}`, // 서버 URL
			},
		],
	},
	apis: ["./src/router/*.js"], // API 명세가 작성된 파일의 경로
};

const specs = swaggerJsdoc(options);

module.exports = {
	swaggerUi,
	specs,
};
